name: Azure Pipelines
variables:
#  python.version: '3.7.6'
- group: project3_variables
stages:
- stage: TerraformIaCCI
  displayName: TerraformIaC - CI
  pool:
    vmImage: 'ubuntu-latest'
  jobs:
  - job: TerraformIaCCIJob
    displayName: TerraformIaCCI - CI Job
    steps:
    # Needed for Terraform VM deployment
    - task: InstallSSHKey@0
      inputs:
        knownHostsEntry: 'KNOWN_HOSTS_STRING'
        sshPublicKey: $(terraform-ssh-pub)
        sshKeySecureFile: 'id_rsa'
    - task: Bash@3
      displayName: Copy ssh rsa pub file for vm.tf
      inputs:
        targetType: 'inline'
        script: cp $(System.DefaultWorkingDirectory)/id_rsa.pub ~/.ssh
    # Step 1: Install Terraform
    - task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-installer.TerraformInstaller@0
      displayName: 'Install Terraform 0.15.3'
      inputs:
        terraformVersion: 0.15.3
    # Step 2: Initialise workspace using terraform init
    - task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-cli.TerraformCLI@0
      displayName: 'terraform init'
      inputs:
        command: init
        workingDirectory: 'Project Starter Resources/terraform'
        backendType: azurerm
        backendServiceArm: 'Azure subscription 1 (753e1116-a934-4cde-98ac-9c70e98003fa)'
        backendAzureRmResourceGroupName: tfstate
        backendAzureRmStorageAccountName: tfstate9935
        backendAzureRmContainerName: qualrel
        backendAzureRmKey: terraform.qualrel
    # Step 3. Validate HCL syntaxt using terraform validate
    - task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-cli.TerraformCLI@0
      displayName: 'terraform validate'    
      inputs:
        command: validate
        workingDirectory: 'Project Starter Resources/terraform'
    # Step 4. Run the terraform plan
    - task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-cli.TerraformCLI@0
      displayName: 'terraform plan'
      inputs:
        command: plan
        workingDirectory: 'Project Starter Resources/terraform'
        environmentServiceName: 'Azure subscription 1 (753e1116-a934-4cde-98ac-9c70e98003fa)'
        commandOptions: -out project3cicd
    # Step 5. Run the terraform apply
    - task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-cli.TerraformCLI@0
      displayName: 'terraform apply'
      inputs:
        provider: 'azurerm'
        command: apply
        workingDirectory: 'Project Starter Resources/terraform'
        environmentServiceName: 'Azure subscription 1 (753e1116-a934-4cde-98ac-9c70e98003fa)'
        commandOptions: project3cicd
- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    # Needed for Terraform VM deployment
    # - task: InstallSSHKey@0
    #   inputs:
    #     knownHostsEntry: 'KNOWN_HOSTS_STRING'
    #     sshPublicKey: 'PUBLIC_KEY'
    #     sshKeySecureFile: 'id_rsa'
    - task: ArchiveFiles@2
      displayName: 'Archive FakeRestAPI'
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)/Project Starter Resources/automatedtesting/jmeter/fakerestapi'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId)-fakerestapi.zip'
    - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId)-fakerestapi.zip
      displayName: 'Upload Package'
      artifact: drop-fakerestapi
- stage:
  jobs:
  - deployment: FakeRestAPI
    pool:
      vmImage: 'ubuntu-latest'
    environment: 'TEST'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            displayName: 'Deploy Azure Web App'
            inputs:
              azureSubscription: 'Azure subscription 1 (753e1116-a934-4cde-98ac-9c70e98003fa)'
              appName: 'proj3_qualrel-AppService'
              appType: webAppLinux
              package: $(Pipeline.Workspace)/drop-fakerestapi/$(Build.BuildId)-fakerestapi.zip
  - deployment: VMDeploy
    displayName: Deployment of Azure VM
    environment:
      name:  TEST
      resourceType: VirtualMachine
  #     tags: TAG NAME
    strategy:
      runOnce:
        deploy:
          steps:
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                #! /bin/bash
                
                sudo apt-get upgrade -y
                sudo apt-get install python3-pip -y
                sudo apt-get install unzip -y
                sudo apt-get install -y chromium-browser
                pip3 install selenium
                export PATH=$PATH:/Users/simonkearn/Documents/Nanodegree
- stage:
  jobs:
  - job: RunThroughPostmanTests
    steps:
    - task: CmdLine@2
      displayName: Install Newman
      inputs:
        script: 'sudo npm install -g newman'
        workingDirectory: $(System.DefaultWorkingDirectory)
    - task: CmdLine@2
      displayName: Run Regression Tests
      continueOnError: true
      inputs:
        script: 'newman run StarterAPIs.json'
        workingDirectory: 'Project Starter Resources/automatedtesting/postman'

